# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=20)),
                ('symptom1', models.CharField(max_length=50)),
                ('symptom2', models.CharField(max_length=50)),
                ('symptom3', models.CharField(max_length=50)),
                ('symptom4', models.CharField(max_length=50)),
                ('symptom5', models.CharField(max_length=50)),
                ('symptom6', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=50)),
                ('question2', models.CharField(max_length=50)),
                ('question3', models.CharField(max_length=50)),
                ('question4', models.CharField(max_length=50)),
                ('question5', models.CharField(max_length=50)),
            ],
        ),
    ]
