# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question1',
            new_name='question_a',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question2',
            new_name='question_b',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question3',
            new_name='question_c',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question4',
            new_name='question_d',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question5',
            new_name='question_e',
        ),
    ]
