# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0003_questions_question_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='symptom1',
            new_name='symptom_list',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question_a',
            new_name='q_a',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question_b',
            new_name='q_b',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question_c',
            new_name='q_c',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question_d',
            new_name='q_d',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question_e',
            new_name='q_e',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question_index',
            new_name='q_index',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptom2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptom3',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptom4',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptom5',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptom6',
        ),
    ]
