# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0004_auto_20181019_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='nickname',
            new_name='sex',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptom_list',
        ),
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(default='Null Name', max_length=30),
        ),
    ]
