# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0005_auto_20181027_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodypart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partname', models.CharField(default='PartName', max_length=100)),
                ('subquestions', models.CharField(default='QuestioName', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
