# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0009_auto_20181027_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(blank=True, max_length=100)),
                ('effect', models.CharField(blank=True, max_length=200)),
                ('rating', models.IntegerField(default=3)),
                ('review_a', models.CharField(blank=True, max_length=1000)),
                ('review_b', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
