# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0010_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='form',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicinesymptom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
