# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0011_auto_20181027_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='amount',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='effect',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='form',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicinename',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicinesymptom',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
