# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0012_auto_20181028_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicineindex',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
