# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0013_medicine_medicineindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicineindex',
            field=models.IntegerField(blank=True),
        ),
    ]
