# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0014_auto_20181028_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
