# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0015_logdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdata',
            name='tmp',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
