# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0016_logdata_tmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdata',
            name='cate',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
